# Placeholders: %recipe_name%
recipe_item:
  material: PAPER
  display_name: '%recipe_name%'
  glint: true


# Full example Gui Border Item
# item:
#   material: GRASS
#   slots: [ 0 ]
#   display_name: 'example item'
#   lore: [ 'example lore', 'another line' ]
#   glint: true
#   custom_model_data: -1
gui:
  title: 'Recipes'
  size: 54
  items:
    recipe_slots: [19, 20, 21, 22, 23, 25, 28, 29, 30, 31, 32, 34]
    next_page:
      material: ARROW
      slots: [53]
      display_name: '&aNext Page'
      lore: [ '&7Click to go to the next page' ]
    previous_page:
      material: ARROW
      slots: [45]
      display_name: '&aPrevious Page'
      lore: [ '&7Click to go to the previous page' ]
  border_items:
    # Border items
    border1:
      material: GREEN_STAINED_GLASS_PANE
      slots: [ 0, 8, 45, 53 ]
      display_name: '&0'
    border2:
      material: GRASS
      slots: [ 1, 7, 46, 52 ]
      display_name: '&0'
    border3:
      material: FERN
      slots: [ 2, 6, 47, 51 ]
      display_name: '&0'
    border4:
      material: PINK_TULIP
      slots: [ 3, 5, 48, 50 ]
      display_name: '&0'
    border5:
      material: LILY_PAD
      slots: [ 4, 49 ]
      display_name: '&0'

messages: