name: BreweryRecipes
version: '${version}'
main: dev.jsinco.breweryrecipes.BreweryRecipes
api-version: '1.20'
author: Jsinco
depend: [Brewery]
commands:
  breweryrecipes:
    description: 'BreweryRecipes command'
    usage: /<command>[reload] <give|givebook|gui>
    permission: breweryrecipes.command